### ISSUE TITLE
添加对于EmueraEM+EE的支持

### ISSUE THREAD

**Issue by EvilMask** [Fegelein21/XEmuera#1]
不知能不能添加对于EmueraEM+EE的支持呢？
您可以在这里找到[源码](https://gitlab.com/EvilMask/emuera.em)，也有[相关文档](https://evilmask.gitlab.io/emuera.em.doc/)，同样是基于`Emuera1824+v15`制作。

除了部分UI以外，修改的部分都以
``` C#
#region EEXXXXXXXXXXX

#endregion
```
或
``` C#
#region EMXXXXXXXXXXX

#endregion
```
的方式包裹。

**Comment by Fegelein21** [comment]
感谢您的提议，我觉得应该等到这边的进度稳定下来了再考虑，目前还不是时候。
